server:
  port: 8003
spring:
  application:
    name: service-provider
  output:
    ansi:
      enabled: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/

