server:
  port: 8001
spring:
  application:
    name: eureka-server
  output:
      ansi:
        enabled: always

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/


