server:
  port: 8001
spring:
  application:
    name: eureka-server
  output:
      ansi:
        enabled: always

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
# 单机下关闭自我保护机制
  server:
    enable-self-preservation: false

